# Config file for automatic testing at travis-ci.org

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
install: pip install coveralls
script: coverage run --source=valideer setup.py test
after_success: coveralls

